[package]
name = "arpoison"
version = "0.1.2"
authors = ["solidus"]
readme = "README.md"
license-file = "LICENSE"
edition = "2018"

[dependencies]
clap    = "2.30"
colored = "2.0.0"
term    = "0.7.0"
pnet_packet = "0.31.0"
pnet = "0.27.1"
